### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by singh-ab** [singh-ab/APS_IIITDMJ#65]
Improve the footer by removing redundant links, adding new links.
![image](https://github.com/user-attachments/assets/d1583769-4e32-449b-8dc0-53d02d9ccfde)
Decrease redundant padding in the footer. Do not however remove the breathing space by removing too much of the space. Make the rotating astronaut a bit smaller if necessary.

**Comment by Harshvardhan1012** [comment]
Hey can I work on this issue @singh-ab

**Comment by singh-ab** [comment]
Sure, I'll assign it to you. You may get the design-related parts further reviewed by @BlackEyes09

**Comment by BlackEyes09** [comment]
Sure, I'm on it.

**Comment by Harshvardhan1012** [comment]
![image](https://github.com/user-attachments/assets/c6c9bc21-8f64-47ea-97ad-5356e03398c5)
I have added the appropiate links and have given some padding 
Some pages are under development so i don't know whether to add their links or not i have added it as of now
also I have added hovering effect to the links
Let me know is this ok so that i can raise pr

**Comment by BlackEyes09** [comment]
So far so good!! We'll keep you updated. Stay tuned.

**Comment by Harshvardhan1012** [comment]
I raised a PR plz review it

**Comment by singh-ab** [comment]
> I raised a PR plz review it

Hi! I've just left a review in your raised PR.

**Comment by Harshvardhan1012** [comment]
I have made the requested changes

**Comment by singh-ab** [comment]
Seems good to go! Closing the issue #66 now.
